image: stablebaselines/rl-baselines3-zoo-cpu:latest

type-check:
  script:
  - make type

pytest:
  script:
  # MKL_THREADING_LAYER=GNU to avoid MKL_THREADING_LAYER=INTEL incompatibility error
  - MKL_THREADING_LAYER=GNU make pytest
